spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1/wechat_order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true